/**
 * WS-A A1 — mapping upstream connection failures to HTTP errors.
 *
 * These errors are generated by the proxy itself (the upstream never
 * answered), so we synthesize an Anthropic-shaped error body that SDK
 * clients can parse, plus an `x-golem-error` marker header so callers can
 * distinguish proxy-generated errors from real upstream responses.
 */

/** Marker header present on every proxy-generated error response. */
export const PROXY_ERROR_HEADER = "x-golem-error";

const TIMEOUT_CODES = new Set([
  "UND_ERR_CONNECT_TIMEOUT",
  "UND_ERR_HEADERS_TIMEOUT",
  "UND_ERR_BODY_TIMEOUT",
  "ETIMEDOUT",
]);

export interface MappedProxyError {
  /** 504 for upstream timeouts, 502 for everything else. */
  readonly status: number;
  /** JSON body, Anthropic error envelope shape. */
  readonly body: string;
}

function errorCode(err: unknown): string | undefined {
  if (err && typeof err === "object") {
    const { code } = err as { code?: unknown };
    if (typeof code === "string") return code;
    const { cause } = err as { cause?: unknown };
    if (cause && cause !== err) return errorCode(cause);
  }
  return undefined;
}

function errorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  return String(err);
}

/** Map an upstream dispatch failure to a client-facing HTTP error. */
export function mapUpstreamError(err: unknown): MappedProxyError {
  const code = errorCode(err);
  const isTimeout = code !== undefined && TIMEOUT_CODES.has(code);
  const status = isTimeout ? 504 : 502;
  const detail = code ? `${code}: ${errorMessage(err)}` : errorMessage(err);
  const message = isTimeout
    ? `golem proxy: upstream request timed out (${detail})`
    : `golem proxy: upstream connection failed (${detail})`;
  const body = JSON.stringify({
    type: "error",
    error: { type: "api_error", message },
  });
  return { status, body };
}
