/**
 * `golem task index` — render the plan-task set as the ROADMAP's open-work table.
 *
 * The point of this command is that **ROADMAP.md stops being the source of truth for
 * task detail** (USER-requested 2026-07-30). Detail lives in one document per task
 * under `docs/plan/tasks/`, so a task can be handed whole to a fresh agent or a
 * separate conversation; the roadmap keeps only a live index of links. Regenerating
 * that index by hand is how it goes stale, so it is generated.
 *
 * Output is Markdown between stable markers, so it can be spliced into ROADMAP.md
 * idempotently — the same marker-fenced technique the brevity directive uses on
 * `system` (Decision 52), and for the same reason: a replaceable region beats a
 * best-effort diff.
 */

import type { Task } from "../tasks/index.js";
import { planTaskSlug, TERMINAL_TASK_STATES } from "../tasks/index.js";

export const PLAN_INDEX_BEGIN = "<!-- golem:task-index:begin -->";
export const PLAN_INDEX_END = "<!-- golem:task-index:end -->";

/** Path a task's document lives at, relative to the repo root. */
export function planTaskLink(task: Task): string {
  return `tasks/${planTaskSlug(task.id)}.md`;
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
}

/**
 * Split tasks into the three groups a reader actually wants: what can be picked up
 * now, what is waiting on the world, and what is finished.
 *
 * `blocked` is a property of the task's own metadata, not of its state — a blocked
 * task is still `queued`, because it is work that exists and will be done, and
 * hiding it in a terminal state is how items get lost (the ROADMAP's own
 * "visible, not lost" rule for its loose ends).
 */
export function groupPlanTasks(tasks: readonly Task[]): {
  ready: Task[];
  blocked: Task[];
  done: Task[];
} {
  const byId = new Map(tasks.map((t) => [t.id, t]));
  const ready: Task[] = [];
  const blocked: Task[] = [];
  const done: Task[] = [];
  for (const task of tasks) {
    if (TERMINAL_TASK_STATES.has(task.state)) {
      done.push(task);
      continue;
    }
    // Waiting on an unfinished dependency counts as blocked without saying so twice.
    const unmetDeps = (task.plan?.dependsOn ?? []).filter((id) => {
      const dep = byId.get(id);
      return dep !== undefined && !TERMINAL_TASK_STATES.has(dep.state);
    });
    if (task.plan?.blocked !== undefined || unmetDeps.length > 0) blocked.push(task);
    else ready.push(task);
  }
  const byIdThenSize = (a: Task, b: Task): number => a.id.localeCompare(b.id, "en");
  ready.sort(byIdThenSize);
  blocked.sort(byIdThenSize);
  done.sort(byIdThenSize);
  return { ready, blocked, done };
}

function row(task: Task): string {
  const plan = task.plan;
  const deps = plan?.dependsOn ?? [];
  const cells = [
    `[${task.id}](${planTaskLink(task)})`,
    escapeCell(task.title ?? task.id),
    plan?.owner ?? "agent",
    plan?.size ?? "M",
    deps.length > 0 ? deps.join(", ") : "—",
    escapeCell(plan?.blocked ?? plan?.gate ?? "—"),
  ];
  return `| ${cells.join(" | ")} |`;
}

const HEADER = [
  "| task | goal | owner | size | depends on | gate / blocker |",
  "|---|---|---|---|---|---|",
];

/**
 * Render the index. Markers are always emitted so the region stays splice-able even
 * when there is nothing in a group.
 */
export function renderPlanIndex(tasks: readonly Task[]): string {
  const { ready, blocked, done } = groupPlanTasks(tasks);
  const out: string[] = [PLAN_INDEX_BEGIN, ""];
  out.push(
    `_Generated by \`golem task index\` from \`docs/plan/tasks/\` — ${ready.length} ready, ` +
      `${blocked.length} blocked, ${done.length} done. Edit the task documents, not this table._`,
  );

  out.push("", "### Ready to pick up", "");
  if (ready.length === 0) out.push("_Nothing ready._");
  else out.push(...HEADER, ...ready.map(row));

  out.push("", "### Blocked or waiting (visible, not lost)", "");
  if (blocked.length === 0) out.push("_Nothing blocked._");
  else out.push(...HEADER, ...blocked.map(row));

  if (done.length > 0) {
    out.push("", "### Closed", "");
    out.push("| task | goal | outcome |", "|---|---|---|");
    for (const task of done) {
      out.push(
        `| [${task.id}](${planTaskLink(task)}) | ${escapeCell(task.title ?? task.id)} | ${task.state} |`,
      );
    }
  }

  out.push("", PLAN_INDEX_END);
  return out.join("\n");
}

/**
 * Splice a freshly-rendered index into a document between the markers.
 *
 * Returns the document unchanged and reports `spliced: false` when the markers are
 * absent, rather than appending: silently adding a second index to a file that was
 * meant to carry one is worse than doing nothing and saying so.
 */
export function splicePlanIndex(
  document: string,
  rendered: string,
): { text: string; spliced: boolean } {
  const start = document.indexOf(PLAN_INDEX_BEGIN);
  const end = document.indexOf(PLAN_INDEX_END);
  if (start === -1 || end === -1 || end < start) return { text: document, spliced: false };
  return {
    text: document.slice(0, start) + rendered + document.slice(end + PLAN_INDEX_END.length),
    spliced: true,
  };
}

/** Human-readable one-screen summary for `golem task index --summary`. */
export function renderPlanSummary(tasks: readonly Task[]): string {
  const { ready, blocked, done } = groupPlanTasks(tasks);
  const lines = [
    `plan tasks — ${ready.length} ready, ${blocked.length} blocked, ${done.length} done`,
    "",
  ];
  for (const [label, group] of [
    ["ready", ready],
    ["blocked", blocked],
  ] as const) {
    if (group.length === 0) continue;
    lines.push(`${label}:`);
    for (const task of group) {
      const plan = task.plan;
      const note = plan?.blocked !== undefined ? `  [blocked: ${plan.blocked}]` : "";
      lines.push(
        `  ${task.id.padEnd(10)} ${(plan?.owner ?? "agent").padEnd(5)} ${(plan?.size ?? "M").padEnd(2)} ` +
          `${task.title ?? task.id}${note}`,
      );
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}
