/**
 * Generate src/version.ts from the canonical package.json `version` (Decision 41a).
 *
 * package.json is the single source of truth for the Golem version; this script
 * keeps the compiled-in `VERSION` constant (src/version.ts, committed and
 * re-exported by src/index.ts) in lockstep. Wired into `npm run build`, and run
 * by scripts/release.mjs after a bump. Cross-platform (node fs), idempotent:
 * only rewrites the file when the content actually changes.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const pkg = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
if (typeof pkg.version !== "string") {
  process.stderr.write("sync-version: package.json has no string `version`\n");
  process.exit(1);
}

const target = join(root, "src", "version.ts");
const content = `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// The single source of truth for the Golem version is package.json (Decision 41a);
// run \`npm run sync-version\` (or \`npm run build\`) to regenerate this file.
export const VERSION = "${pkg.version}";
`;

const existing = await readFile(target, "utf8").catch(() => null);
if (existing === content) {
  process.stdout.write(`sync-version: src/version.ts already at ${pkg.version}\n`);
} else {
  await writeFile(target, content, "utf8");
  process.stdout.write(`sync-version: wrote src/version.ts (VERSION = ${pkg.version})\n`);
}
