// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// The single source of truth for the Golem version is package.json (Decision 41a);
// run `npm run sync-version` (or `npm run build`) to regenerate this file.
export const VERSION = "0.26.0";
